### ISSUE TITLE
`memory-storage` and `sled-storage` features not working

### ISSUE THREAD

**Issue by panarch** [gluesql/gluesql#468]
```toml
[dependencies.gluesql]
version = "0.10.1"
default-features = false
features = ["memory-storage"]
```

This kind of config should work but it does not.
