### ISSUE TITLE
"error[E0433]: failed to resolve: use of undeclared type `SledStorage`" Issue

### ISSUE THREAD

**Issue by Raj2032** [gluesql/gluesql#604]
So I have a very simple code:

```rust
use gluesql::prelude::*;

fn main()
{
    let storage = SledStorage::new("test_db").unwrap();
    let mut glue = Glue::new(storage);
}

```

And in my `Cargo.toml` file this is my stuff in it:

```toml
[package]
name = "testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.gluesql]
version = "0.11"
default-features = false
features = ["alter-table", "index", "transaction", "metadata"]
```

So when I run a `cargo run` this is the error I get (after it compiles and stuff):

```cmd
error[E0433]: failed to resolve: use of undeclared type `SledStorage`
 --> src\main.rs:5:19
  |
5 |     let storage = SledStorage::new("test_db").unwrap();
  |                   ^^^^^^^^^^^ use of undeclared type `SledStorage`
```

Not sure why this is happening?

**Comment by ever0de** [comment]
It's not a bug.

excerpt from root workspace
`sled-storage = { package = "gluesql_sled_storage", path = "./storages/sled-storage", version = "0.11.0", optional = true }`

Since sled-storage is also optional, it is classified as a feature.
Do not enable the `sled-storage` feature or turn off default-features .

**Comment by Raj2032** [comment]
@ever0de How would I use the `sled-storage` feature though?

**Comment by ever0de** [comment]
example `Cargo.toml`

```toml
[dependencies]
gluesql = "0.11"
```

Would you like to add this and test it?
